language: node_js
node_js:
  - "10"
before_install:
# Create a master branch for commitlint
# https://github.com/conventional-changelog/commitlint/issues/6
  - git remote set-branches origin master && git fetch