name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10.x', '12.x', '14.x' ]
    name: Node ${{ matrix.node }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        git remote set-branches --add origin main
        git fetch
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install Dependencies
      run: yarn
      env:
        NODE_ENV: development
    - name: Unit Tests
      run: yarn test:unit
    - name: Git History Test
      run: yarn test:git-history
    - name: Lockfile Lint Test
      run: yarn test:lockfile
    - name: Lint
      run: yarn lint
